#! /bin/bash

mpdRunning=$(pgrep -x mpd) 
ncmpcpp=$(pgrep -x ncmpcpp)
mpc=$(mpc | grep playing) 


if [ $1 == playPause ]
then
    if [ -z "$mpc" ]
    then 
        mpc play 
    else
        mpc pause
    fi
fi
  
if [ $1 == startMusic ]
    then
        if [ -z "$mpdRunning" ]  
        then
            mpd
            if [ -z "$ncmpcpp" ]
            then 
                alacritty -e ncmpcpp
            fi
        else
            killall mpd
            if [ -n "$ncmpcpp" ]
            then 
                killall alacritty
            fi
        fi
fi

# File Converter  


function convertNoToDir {
    dirNo="$dir"
    dir=
    while [ "$dirNo" -ge 1 ]
    do
        dir+=.
        placeHolder=$(printf "%${dirNo}s");dir+=${placeHolder// //*}
        dir+=.$OrgFormat" "
        dirNo=$((dirNo-1))
        echo $dir
    done
}

if [ "$1" == converter ] 
then 
    echo "What is the original Format?, use .Filename (e.g ogg, mp3, flac)" 
    
    read -r OrgFormat
    
    OrgFormat="${OrgFormat//.}"

    echo "What is the Format you wish to convert to, also use the .Filename (e.g ogg, mp3, flac)"
    
    read -r Output
    
    Output="${Output//.}"
    
    echo "How far down yould you like to convert the files, current directory is 1, one layer down is 2 etc,"
    
    read -r dir
    convertNoToDir
    echo "This will convert ALL the files in the current directory/ies selected continue? (y/N)"
    
    read -r Y
        if [ ! "$Y" = y ]
        then 
            exit  
        fi

        for i in $dir ; do ffmpeg -i "$i" "${i%.*}"."$Output"; done
        exit 
fi
        